"txt modLast login: Tue Aug 12 10:38:33 on ttys000 c% ➜  ~ cd Desktop/techgo ➜  techgo ls admin                        own_projects exercices                    projects final project                projects-drafts keyboard-shortcuts-macos.pdf spring-2025-live-sessions notes ➜  techgo cd  projects ➜  projects ls js-project-accessibility  js-project-movies         js-project-weather-app js-project-api            js-project-portfolio      project-final js-project-business-site  js-project-recipe-library js-project-happy-thoughts js-project-todo ➜  projects cd project-final ➜  project-final git:(3D-env) ls Procfile          backend           node_modules      package.json README.md         frontend          package-lock.json todo.md ➜  project-final git:(3D-env) cd frontend ➜  frontend git:(3D-env) git add . ➜  frontend git:(3D-env) ✗ git commit -m "changed 3D scene backgroung color" [3D-env 8b80222] changed 3D scene backgroung color  2 files changed, 14 insertions(+), 3 deletions(-) ➜  frontend git:(3D-env) ✗ git push Enumerating objects: 15, done. Counting objects: 100% (15/15), done. Delta compression using up to 16 threads Compressing objects: 100% (7/7), done. Writing objects: 100% (8/8), 755 bytes | 755.00 KiB/s, done. Total 8 (delta 4), reused 0 (delta 0), pack-reused 0 (from 0) remote: Resolving deltas: 100% (4/4), completed with 4 local objects. To https://github.com/HolaCarmensita/project-final.git    cd9c6f4..8b80222  3D-env -> 3D-env ➜  frontend git:(3D-env) ✗ git pull Already up to date. ➜  frontend git:(3D-env) ✗ git add . ➜  frontend git:(3D-env) ✗ git commit -m "color orbits" [3D-env 19fee9b] color orbits  2 files changed, 59 insertions(+), 19 deletions(-) ➜  frontend git:(3D-env) ✗ git push Enumerating objects: 15, done. Counting objects: 100% (15/15), done. Delta compression using up to 16 threads Compressing objects: 100% (7/7), done. Writing objects: 100% (8/8), 1.71 KiB | 92.00 KiB/s, done. Total 8 (delta 4), reused 0 (delta 0), pack-reused 0 (from 0) remote: Resolving deltas: 100% (4/4), completed with 4 local objects. To https://github.com/HolaCarmensita/project-final.git    8b80222..19fee9b  3D-env -> 3D-env ➜  frontend git:(3D-env) ✗ git add . ➜  frontend git:(3D-env) ✗ git commit -m "removed text and fixed small bug" [3D-env 4d7f3c6] removed text and fixed small bug  2 files changed, 9 insertions(+), 30 deletions(-) ➜  frontend git:(3D-env) ✗ git push Enumerating objects: 15, done. Counting objects: 100% (15/15), done. Delta compression using up to 16 threads Compressing objects: 100% (7/7), done. Writing objects: 100% (8/8), 687 bytes | 62.00 KiB/s, done. Total 8 (delta 5), reused 0 (delta 0), pack-reused 0 (from 0) remote: Resolving deltas: 100% (5/5), completed with 5 local objects. To https://github.com/HolaCarmensita/project-final.git    19fee9b..4d7f3c6  3D-env -> 3D-env ➜  frontend git:(3D-env) ✗ npm i randomcolor
added 1 package, and audited 341 packages in 868ms

115 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
➜  frontend git:(3D-env) ✗ git add .
➜  frontend git:(3D-env) ✗ git commit -m "added navigation, click on sphere and
so on"
[3D-env b079892] added navigation, click on sphere and so on
 4 files changed, 144 insertions(+), 45 deletions(-)
 create mode 100644 frontend/src/pages/3DScene/CameraController.jsx
➜  frontend git:(3D-env) ✗ git push
Enumerating objects: 18, done.
Counting objects: 100% (18/18), done.
Delta compression using up to 16 threads
Compressing objects: 100% (9/9), done.
Writing objects: 100% (10/10), 3.22 KiB | 824.00 KiB/s, done.
Total 10 (delta 5), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
To https://github.com/HolaCarmensita/project-final.git
   4d7f3c6..b079892  3D-env -> 3D-env
➜  frontend git:(3D-env) ✗ npm install gsap

added 1 package, and audited 342 packages in 6s

115 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
➜  frontend git:(3D-env) ✗ git add .
➜  frontend git:(3D-env) ✗ git commit -m "animation on click"
[3D-env 18e892d] animation on click
 2 files changed, 21 insertions(+), 6 deletions(-)
➜  frontend git:(3D-env) ✗ git push
Enumerating objects: 15, done.
Counting objects: 100% (15/15), done.
Delta compression using up to 16 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (8/8), 943 bytes | 188.00 KiB/s, done.
Total 8 (delta 5), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
To https://github.com/HolaCarmensita/project-final.git
   b079892..18e892d  3D-env -> 3D-env
➜  frontend git:(3D-env) ✗ git add .
➜  frontend git:(3D-env) ✗ git commit -m "updated to do"
On branch 3D-env
Your branch is up to date with 'origin/3D-env'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   ../todo.md

no changes added to commit (use "git add" and/or "git commit -a")
➜  frontend git:(3D-env) ✗ git push
Everything up-to-date
➜  frontend git:(3D-env) ✗ git checkout dev
error: Your local changes to the following files would be overwritten by checkout:
	todo.md
Please commit your changes or stash them before you switch branches.
Aborting
➜  frontend git:(3D-env) ✗ git checkout dev
error: Your local changes to the following files would be overwritten by checkout:
	todo.md
Please commit your changes or stash them before you switch branches.
Aborting
➜  frontend git:(3D-env) ✗ git branch -a
txt mod
txt mod
"txt mod"
"txt mod"q
"txt mod"
"txt mod"
~
~
~
~
~
~
~
~
~
~
~
~
~
~
-- INSERT --
Update todo.md with latest changes